import time
import turtle

screen= turtle.Screen()
screen.bgcolor("white")
screen.title("Assignment 1_wrist watch(clock)")
screen.setup(width=1000,height=1000)
screen.tracer(0)
#let our trtles name be max, jack, and alex, where alex and jack draw the parts that hold wrist and max draws all the rest.
max = turtle.Turtle()
jack=turtle.Turtle()
alex = turtle.Turtle()
max.hideturtle()
jack.hideturtle()
alex.hideturtle()
dot = turtle.Turtle()

dot.shape("circle")
dot.pencolor("white")
dot.setpos(0,0)
dot.setheading(0)
dot.forward(1)

def for_wrist1(jack):
    jack.penup()
    jack.setpos(75,290.47)
    jack.setheading(90)
    jack.pendown()
    jack.fillcolor("black")
    jack.begin_fill()
    jack.forward(200)
    jack.penup()
    jack.setpos(-75,290.47)
    jack.setheading(90)
    jack.pendown()
    jack.forward(200)
    jack.end_fill()

def for_wrist2(alex):
    alex.penup()
    alex.setpos(75,-290.47)
    alex.setheading(-90)
    alex.pendown()
    alex.fillcolor("black")
    alex.begin_fill()
    alex.forward(200)
    alex.penup()
    alex.setpos(-75,-290.47)
    alex.setheading(-90)
    alex.pendown()
    alex.forward(200)
    alex.end_fill()

def my_clock(hour, minute, second,max,):
    max.penup()
    max.setpos(0,300)
    max.setheading(180)
    max.color("blue")
    max.pendown()
    max.pensize(6)
    max.fillcolor("black")
    max.begin_fill()
    max.circle(300)
    max.end_fill()
    max.penup()
    max.setpos(0, 0)
    max.setheading(90)

    for i in range(12):
        max.forward(280)
        max.pendown()
        max.forward(20)
        max.penup()
        max.setpos(0, 0)
        max.right(30)
    
    max.penup()
    max.setpos(0,0)
    max.setheading(90)

    for i in range(60):
        max.forward(290)
        max.pendown()
        max.forward(10)
        max.penup()
        max.setpos(0,0)
        max.right(6)
    
    max.penup()
    max.setpos(0,0)
    max.setheading(59)
    max.forward(260)
    max.setheading(0)
    max.write(1,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(28)
    max.forward(262)
    max.setheading(0)
    max.write(2,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(356.5)
    max.forward(269)
    max.setheading(0)
    max.write(3,align="center",font=("roman", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(326)
    max.forward(271)
    max.setheading(0)
    max.forward(8)
    max.write(4,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(297)
    max.forward(271)
    max.setheading(0)
    max.forward(12)
    max.write(5,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(267.6)
    max.forward(280)
    max.setheading(0)
    max.forward(12)
    max.write(6,align="center",font=("roman", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(240)
    max.forward(285)
    max.setheading(0)
    max.forward(12)
    max.write(7,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(212.5)
    max.forward(287)
    max.setheading(0)
    max.forward(12)
    max.write(8,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(183)
    max.forward(281)
    max.setheading(0)
    max.forward(12)
    max.write(9,align="center",font=("roman", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(153)
    max.forward(265)
    max.setheading(0)
    max.forward(12)
    max.write(10,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(123)
    max.forward(255)
    max.setheading(0)
    max.forward(12)
    max.write(11,align="center",font=("courier", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.setheading(92)
    max.forward(253)
    max.setheading(0)
    max.forward(10)
    max.write(12,align="center",font=("roman", 20, "bold"))

    max.penup()
    max.setpos(0,0)
    max.pencolor("white")
    max.setheading(268)
    max.forward(120)
    max.setheading(0)
    max.write("Designed by Gemechis Urgessa", align = "center", font=("Arial", 13,"bold"))

    ourtime_format = (hour,minute,second)
    clock_hands = [("red", 85, 12, 5, "arrow"), ("green", 110, 60, 4,"arrow"), ("white", 130, 60,2,"arrow")]

    for i in clock_hands:
        time_set = ourtime_format[clock_hands.index(i)]
        max.penup()
        max.goto(0, 0)
        max.shape(i[4])
        max.color(i[0])
        max.pensize(i[3])
        max.setheading(90)
        max.right((time_set/i[2])*360)
        max.pendown()
        max.forward(i[1])
        max.stamp()


while True:
    hour = int(time.strftime("%I"))
    minute = int(time.strftime("%M"))
    second = time.time()

    my_clock(hour, minute, second, max,)
    for_wrist2(alex)
    for_wrist1(jack)
    screen.update()
    time.sleep(1)
    max.clear()
    

    